version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "gradle-build-action"
      - dependency-name: "wrapper-validation-action"
